# Generated by Django 3.1.2 on 2020-10-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20201023_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='writtem_phone',
            field=models.CharField(max_length=12, verbose_name='Ваш телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_cover_letter',
            field=models.TextField(verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_username',
            field=models.CharField(max_length=100, verbose_name='Вас зовут'),
        ),
    ]
